services:
  app:
    container_name: essay-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '${APP_PORT}:3000'
    volumes:
      - app_uploads:/app/uploads
      - app_logs:/app/logs
    networks:
      - app-network
    command: sh -c "npx prisma migrate deploy && node dist/prisma/seed.js && node dist/main"
  db:
    container_name: essay-db
    image: postgres:17
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - app-network

volumes:
  db_data:
  app_uploads:
  app_logs:

networks:
  app-network:
    driver: bridge
